# This file is created by Streamlit Cloud deployment
# It indicates the app is running in a cloud environment

# Cloud deployment settings
CLOUD_DEPLOYMENT = True
AUDIO_ENABLED = False
SCREEN_CAPTURE_ENABLED = False
DEMO_MODE = True